# Generated by Django 6.0.4 on 2026-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionplan",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="revisionplan",
            name="goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="revisionplan",
            name="priority",
            field=models.CharField(
                choices=[("low", "Faible"), ("medium", "Moyenne"), ("high", "Élevée")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
