# Generated by Django 6.0.5 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepdf',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
